"""
Django settings for SGA project.

Generated by 'django-admin startproject' using Django 4.2.11.
Updated for Docker, Django Channels (ASGI), PostgreSQL and Redis.
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# =============================================================================
# SECURITY SETTINGS
# =============================================================================

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-r#f7)g%=rdp8ld331qv3q5-43qlivp_@^)r0tk8o!7ar3=_710')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG =  True
#os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '192.168.0.213,localhost,127.0.0.1,0.0.0.0,192.168.1.191,192.168.1.192,sigap-1.onrender.com').split(',')

# CSRF Trusted Origins (para Docker/produção)
# CSRF Trusted Origins (para Docker/produção)
CSRF_TRUSTED_ORIGINS_ENV = os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
CSRF_TRUSTED_ORIGINS_DEFAULT = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://192.168.1.191',
    'http://192.168.1.191:8000',
    'http://192.168.1.192',
    'http://192.168.1.192:8000',
    'https://sigap-1.onrender.com'
]
CSRF_TRUSTED_ORIGINS = list(filter(None, set(CSRF_TRUSTED_ORIGINS_ENV + CSRF_TRUSTED_ORIGINS_DEFAULT)))


# =============================================================================
# APPLICATION DEFINITION
# =============================================================================

INSTALLED_APPS = [
    # Django Channels (WebSockets/ASGI)
    'channels',

    # Django Core
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Apps do Projeto
    'ARQUIVOS',

    # Editor de Texto Rico
    'tinymce',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise: logo após SecurityMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'ARQUIVOS.middleware.SecurityAuditMiddleware',
]

ROOT_URLCONF = 'SGA.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'Paginas'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'ARQUIVOS.context_processors.notificacoes_context',
            ],
        },
    },
]

# WSGI (fallback) e ASGI (principal)
WSGI_APPLICATION = 'SGA.wsgi.application'
ASGI_APPLICATION = 'SGA.asgi.application'


# =============================================================================
# CHANNELS / REDIS CONFIGURATION
# =============================================================================

# Redis URL para Channel Layer
REDIS_URL = os.environ.get('REDIS_URL', 'redis://redis:6379/0')

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL,],
        },
    },
}

# Fallback para desenvolvimento sem Redis

# =============================================================================
# CACHE CONFIGURATION
# =============================================================================



# =============================================================================
# DATABASE CONFIGURATION
# =============================================================================

import dj_database_url

# No Render (produção): usar DATABASE_URL (link INTERNO, mais rápido)
# Localmente (sem Docker): usar BD PostgreSQL local (sga_db)
DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    # Produção (Render) ou Docker local — DATABASE_URL definida como variável de ambiente
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600, conn_health_checks=True)
    }
else:
    # Fallback local (sem Docker) — PostgreSQL local
    DATABASES = {
        'default': dj_database_url.parse(
            "postgresql://sga_user:sga_password@localhost:5432/sga_db",
            conn_max_age=600,
            conn_health_checks=True,
        )
    }


# =============================================================================
# PASSWORD VALIDATION
# =============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# =============================================================================
# INTERNATIONALIZATION
# =============================================================================

LANGUAGE_CODE = 'pt-ao'
TIME_ZONE = 'Africa/Luanda'
USE_I18N = True
USE_TZ = True


# =============================================================================
# AUTHENTICATION
# =============================================================================

AUTH_USER_MODEL = 'ARQUIVOS.CustomUser'
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'Painel/'
LOGOUT_REDIRECT_URL = '/'


# =============================================================================
# STATIC & MEDIA FILES
# =============================================================================

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'ARQUIVOS' / 'static',
]

# WhiteNoise: Compressão e Cache de Arquivos Estáticos
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
WHITENOISE_USE_FINDERS = True       # Ajuda a encontrar arquivos em desenvolvimento

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# =============================================================================
# DEFAULT PRIMARY KEY FIELD TYPE
# =============================================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =============================================================================
# LOGGING (para debug)
# =============================================================================

if DEBUG:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
            },
        },
        'loggers': {
            'django.channels': {
                'handlers': ['console'],
                'level': 'DEBUG',
            },
        },
    }
