# Generated by Django 4.2.13 on 2025-09-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0003_departamento_parent_departamento_tipo_municipio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='tipo_departamento',
            field=models.CharField(choices=[('A', 'Tipo A'), ('B', 'Tipo B'), ('C', 'Tipo C'), ('E', 'Tipo E')], default='A', max_length=1, verbose_name='Tipo de Departamento'),
        ),
    ]
