# Generated by Django 4.2.13 on 2025-09-07 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0004_departamento_tipo_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='status',
            field=models.CharField(choices=[('criacao', 'Criação'), ('recebimento', 'Recebimento'), ('encaminhamento', 'Encaminhamento'), ('despacho', 'Despacho'), ('aprovado', 'Aprovado'), ('reprovado', 'reprovado'), ('arquivado', 'arquivado')], default='recebido', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimentacaodocumento',
            name='tipo_movimentacao',
            field=models.CharField(choices=[('criacao', 'Criação'), ('recebimento', 'Recebimento'), ('encaminhamento', 'Encaminhamento'), ('despacho', 'Despacho'), ('aprovado', 'Aprovado'), ('reprovado', 'reprovado'), ('arquivado', 'arquivado')], max_length=20),
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True, max_length=255, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('lida', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
