# Generated by Django 4.2.11 on 2025-12-20 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0007_alter_departamento_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='seccao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ARQUIVOS.seccoes'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nivel_acesso',
            field=models.CharField(choices=[('operador', 'Operador'), ('supervisor', 'Supervisor'), ('gerente', 'Gerente'), ('diretor', 'Diretor'), ('admin', 'Administrador'), ('administrador', 'Administrador Municipal'), ('diretor', 'Director Municipal / Chefe de Gabinete'), ('chefe_seccao', 'Chefe de Secção'), ('tecnico', 'Técnico Superior / Especialista'), ('escriturario', 'Assistente Técnico / Escriturário'), ('ti_admin', 'Administrador de Sistema (TI)')], default='operador', max_length=20),
        ),
    ]
