# Generated by Django 4.2.11 on 2025-12-21 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0011_movimentacaodocumento_seccao_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_departamento', to='ARQUIVOS.departamento'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nivel_acesso',
            field=models.CharField(choices=[('admin_sistema', 'Administrador de Sistema'), ('admin_municipal', 'Administrador Municipal'), ('diretor_municipal', 'Director Municipal'), ('chefe_gabinete', 'Chefe de Gabinete'), ('chefe_seccao', 'Chefe de Secção'), ('supervisor', 'Supervisor'), ('tecnico', 'Técnico Superior/Especialista'), ('escriturario', 'Assistente Técnico/Escriturário'), ('operador', 'Operador')], default='operador', max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='seccao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_seccao', to='ARQUIVOS.seccoes'),
        ),
    ]
