# Generated by Django 4.2.11 on 2025-12-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0014_documento_seccao_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='data_ultima_movimentacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='prioridade',
            field=models.CharField(choices=[('urgente', 'Urgente 🔥'), ('alta', 'Alta 🔴'), ('media', 'Média 🟡'), ('baixa', 'Baixa 🟢')], default='normal', max_length=10),
        ),
    ]
