# Generated by Django 4.2.11 on 2025-12-24 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0015_documento_data_ultima_movimentacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='seccao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
