# Generated by Django 4.2.11 on 2025-12-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0016_notificacao_departamento_notificacao_seccao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='data_prazo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='status',
            field=models.CharField(choices=[('criacao', 'Criação'), ('recebimento', 'Recebimento'), ('encaminhamento', 'Encaminhamento'), ('despacho', 'Despacho'), ('aprovado', 'Aprovado'), ('reprovado', 'reprovado'), ('arquivado', 'arquivado')], default='encaminhamento', max_length=20),
        ),
    ]
