# Generated by Django 4.2.13 on 2026-01-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0019_documento_nivels_documento_referencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='origem',
            field=models.CharField(choices=[('Pessoa Singular', 'Pessoa Singular'), ('Instituição do Estado', 'Instituição do Estado'), ('Instituição Pública', 'Instituição Pública'), ('Instituição Privada', 'Instituição Privada'), ('Organização cívil', 'Organização cívil')], default='Pessoa Singular', max_length=52, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='Entidade',
            field=models.CharField(choices=[('Pessoa Singular', 'Pessoa Singular'), ('Instituição do Estado', 'Instituição do Estado'), ('Instituição Pública', 'Instituição Pública'), ('Instituição Privada', 'Instituição Privada'), ('Organização cívil', 'Organização cívil')], default='Pessoa Singular', max_length=52),
        ),
    ]
