# Generated by Django 4.2.11 on 2026-01-12 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0021_provincia_alter_customuser_departamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administracao',
            name='provincia',
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='municipios', to='ARQUIVOS.provincia')),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
            },
        ),
        migrations.AddField(
            model_name='administracao',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='administracoes', to='ARQUIVOS.municipio'),
        ),
    ]
