# Generated by Django 4.2.11 on 2026-01-12 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0024_customuser_administracao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmazenamentoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estante', models.CharField(blank=True, help_text='Código/Nome da Estante', max_length=50)),
                ('prateleira', models.CharField(blank=True, help_text='Código/Nome da Prateleira', max_length=50)),
                ('dossie', models.CharField(blank=True, help_text='Código/Nome do Dossiê', max_length=50)),
                ('caixa', models.CharField(blank=True, help_text='Código/Nome da Caixa (opcional)', max_length=50)),
                ('posicao', models.CharField(blank=True, help_text='Posição específica dentro do local', max_length=50)),
                ('data_armazenamento', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o documento ainda está neste local')),
                ('data_retirada', models.DateTimeField(blank=True, help_text='Data em que o documento foi retirado deste local', null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('motivo_movimentacao', models.CharField(blank=True, help_text='Motivo da movimentação (consulta, reencaminhamento, etc)', max_length=100)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armazenamentos', to='ARQUIVOS.documento')),
            ],
            options={
                'verbose_name': 'Armazenamento de Documento',
                'verbose_name_plural': 'Armazenamentos de Documentos',
                'ordering': ['-data_armazenamento'],
            },
        ),
        migrations.CreateModel(
            name='LocalArmazenamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único do local (ex: EST-01, PRAT-01-A, DOS-001)', max_length=50, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('estante', 'Estante'), ('prateleira', 'Prateleira'), ('dossie', 'Dossiê'), ('caixa', 'Caixa'), ('armario', 'Armário'), ('pasta', 'Pasta')], default='estante', max_length=20)),
                ('capacidade_maxima', models.IntegerField(default=0, help_text='Capacidade máxima de documentos/dossiês (0 = ilimitado)')),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Local de Armazenamento',
                'verbose_name_plural': 'Locais de Armazenamento',
                'ordering': ['departamento', 'tipo', 'codigo'],
            },
        ),
        migrations.RemoveField(
            model_name='administracao',
            name='municipio',
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='administracao',
        ),
        migrations.DeleteModel(
            name='Municipio',
        ),
        migrations.DeleteModel(
            name='Provincia',
        ),
        migrations.AddField(
            model_name='localarmazenamento',
            name='departamento',
            field=models.ForeignKey(help_text='Departamento onde este local está fisicamente', on_delete=django.db.models.deletion.CASCADE, related_name='locais_armazenamento', to='ARQUIVOS.departamento'),
        ),
        migrations.AddField(
            model_name='localarmazenamento',
            name='local_pai',
            field=models.ForeignKey(blank=True, help_text='Local pai na hierarquia (ex: Prateleira pertence a uma Estante)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locais_filhos', to='ARQUIVOS.localarmazenamento'),
        ),
        migrations.AddField(
            model_name='localarmazenamento',
            name='seccao',
            field=models.ForeignKey(blank=True, help_text='Secção específica (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locais_armazenamento', to='ARQUIVOS.seccoes'),
        ),
        migrations.AddField(
            model_name='armazenamentodocumento',
            name='local_armazenamento',
            field=models.ForeignKey(blank=True, help_text='Local cadastrado no sistema', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='armazenamentos', to='ARQUIVOS.localarmazenamento'),
        ),
        migrations.AddField(
            model_name='armazenamentodocumento',
            name='movimentacao_origem',
            field=models.ForeignKey(blank=True, help_text='Movimentação que gerou este registro de armazenamento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='armazenamentos', to='ARQUIVOS.movimentacaodocumento'),
        ),
        migrations.AddField(
            model_name='armazenamentodocumento',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='armazenamentos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='armazenamentodocumento',
            name='retirado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='armazenamentos_retirados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='administracao',
        ),
        migrations.DeleteModel(
            name='Administracao',
        ),
    ]
