# Generated by Django 4.2.11 on 2026-01-13 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0025_armazenamentodocumento_localarmazenamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_departamento', to='ARQUIVOS.departamento'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='seccao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_seccao', to='ARQUIVOS.seccoes'),
        ),
    ]
