# Generated by Django 4.2.11 on 2026-01-13 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0026_fix_notificacao_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacao',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='seccao',
        ),
    ]
