# Generated by Django 4.2.11 on 2026-01-17 23:29

import ARQUIVOS.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0035_populate_generic_departments'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', ARQUIVOS.managers.UsuarioManager()),
            ],
        ),
        migrations.AddField(
            model_name='administracao',
            name='provincia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
