# Generated by Django 4.2.11 on 2026-01-18 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0036_alter_customuser_managers_administracao_provincia'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='administracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='ARQUIVOS.administracao'),
        ),
    ]
