# Generated by Django 4.2.11 on 2026-01-18 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0039_populate_orphan_administracoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='administracao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios_administracao', to='ARQUIVOS.administracao'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='administracao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos_especificos', to='ARQUIVOS.administracao'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='administracao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='ARQUIVOS.administracao'),
        ),
    ]
