# Generated by Django for organizational structure
from django.db import migrations


# ========================================
# ESTRUTURA ORGANIZACIONAL POR TIPO
# ========================================

DEPARTAMENTOS_TIPO_A = [
    # Gabinetes
    {"nome": "Gabinete do Administrador Municipal", "codigo": "GAB-AM"},
    {"nome": "Gabinete do Administrador Adjunto (Área Política, Social e da Comunidade)", "codigo": "GAB-AMA-PSC"},
    {"nome": "Gabinete do Administrador Adjunto (Área Técnica e Infra-estruturas)", "codigo": "GAB-AMA-TI"},
    {"nome": "Gabinete do Administrador Adjunto (Área Económica e Financeira)", "codigo": "GAB-AMA-EF"},
    {"nome": "Secretaria Geral", "codigo": "SG"},
    {"nome": "Gabinete de Estudos, Planeamento e Estatística", "codigo": "GEPE"},
    {"nome": "Gabinete de Recursos Humanos", "codigo": "GRH"},
    {"nome": "Gabinete Jurídico, Intercâmbio e Apoio às Comissões de Moradores", "codigo": "GJ-ICM"},
    {"nome": "Gabinete de Comunicação Social", "codigo": "GCS"},
    # Direcções
    {"nome": "Direcção Municipal da Educação", "codigo": "DME"},
    {"nome": "Direcção Municipal da Saúde", "codigo": "DMS"},
    {"nome": "Direcção Municipal de Promoção do Desenvolvimento Económico", "codigo": "DM-PDE"},
    {"nome": "Direcção Municipal do Ambiente e Saneamento Básico", "codigo": "DM-ASB"},
    {"nome": "Direcção Municipal dos Transportes, Tráfego e Mobilidade", "codigo": "DM-TTM"},
    {"nome": "Direcção Municipal da Acção Social, Família e Igualdade do Género", "codigo": "DM-ASFIG"},
    {"nome": "Direcção Municipal do Turismo e Cultura", "codigo": "DM-TC"},
    {"nome": "Direcção Municipal de Energia e Águas", "codigo": "DM-EA"},
    {"nome": "Direcção Municipal de Infra-Estruturas, Ordenamento do Território e Habitação", "codigo": "DM-IOTH"},
    {"nome": "Direcção Municipal de Agricultura, Pecuária e Pescas", "codigo": "DM-APP"},
    {"nome": "Direcção Municipal dos Registos e Modernização Administrativa", "codigo": "DM-RMA"},
    {"nome": "Direcção Municipal de Tempos Livres, Juventude e Desportos", "codigo": "DM-TLJD"},
    {"nome": "Direcção Municipal de Fiscalização e Inspecção", "codigo": "DM-FI"},
]

DEPARTAMENTOS_TIPO_B = [
    {"nome": "Gabinete do Administrador Municipal", "codigo": "GAB-AM"},
    {"nome": "Gabinete do Administrador Adjunto (Área Política e Social)", "codigo": "GAB-AMA-PS"},
    {"nome": "Gabinete do Administrador Adjunto (Área Técnica e Económica)", "codigo": "GAB-AMA-TE"},
    {"nome": "Secretaria Geral", "codigo": "SG"},
    {"nome": "Gabinete de Estudos, Planeamento e Recursos Humanos", "codigo": "GEPRH"},
    {"nome": "Direcção Municipal de Educação e Saúde", "codigo": "DMES"},
    {"nome": "Direcção Municipal de Infra-estruturas e Serviços Técnicos", "codigo": "DM-IST"},
    {"nome": "Direcção Municipal de Agricultura, Pecuária e Pescas", "codigo": "DM-APP"},
    {"nome": "Direcção Municipal de Acção Social e Família", "codigo": "DM-ASF"},
    {"nome": "Direcção Municipal de Energia e Águas", "codigo": "DM-EA"},
    {"nome": "Direcção Municipal dos Registos e Modernização Administrativa", "codigo": "DM-RMA"},
    {"nome": "Direcção Municipal de Fiscalização", "codigo": "DM-F"},
]

DEPARTAMENTOS_TIPO_C = [
    {"nome": "Gabinete do Administrador Municipal", "codigo": "GAB-AM"},
    {"nome": "Gabinete do Administrador Municipal Adjunto", "codigo": "GAB-AMA"},
    {"nome": "Secretaria Municipal", "codigo": "SM"},
    {"nome": "Repartição de Planeamento e Serviços Sociais", "codigo": "RPSS"},
    {"nome": "Repartição de Serviços Técnicos", "codigo": "RST"},
    {"nome": "Repartição de Agricultura e Pescas", "codigo": "RAP"},
    {"nome": "Repartição de Educação e Saúde", "codigo": "RES"},
    {"nome": "Repartição de Registos e Notariado", "codigo": "RRN"},
    {"nome": "Repartição de Fiscalização Económica", "codigo": "RFE"},
]

DEPARTAMENTOS_TIPO_D = [
    {"nome": "Gabinete do Administrador Municipal", "codigo": "GAB-AM"},
    {"nome": "Repartição de Administração e Serviços Gerais", "codigo": "RASG"},
    {"nome": "Repartição de Serviços Sociais e Económicos", "codigo": "RSSE"},
    {"nome": "Repartição de Serviços Técnicos e Infra-estruturas", "codigo": "RSTI"},
    {"nome": "Repartição de Agricultura", "codigo": "RA"},
    {"nome": "Repartição de Registos", "codigo": "RR"},
    {"nome": "Repartição de Fiscalização", "codigo": "RF"},
]

# Secções padrão por departamento (código do dept -> lista de secções)
SECCOES_POR_DEPARTAMENTO = {
    "SG": [
        "Secção de Expediente e Arquivo",
        "Secção de Património",
        "Secção de Protocolo",
    ],
    "GRH": [
        "Secção de Cadastro e Gestão de Pessoal",
        "Secção de Formação",
    ],
    "DME": [
        "Secção de Ensino Primário",
        "Secção de Ensino Secundário",
        "Secção de Alfabetização e Educação de Adultos",
    ],
    "DMS": [
        "Secção de Programas de Saúde",
        "Secção de Estatística Sanitária",
        "Secção de Farmácias e Medicamentos",
    ],
    "DM-RMA": [
        "Secção de Registo Civil",
        "Secção de Identificação Civil",
        "Secção de Notariado",
    ],
    "SM": [
        "Secção de Expediente",
        "Secção de Arquivo",
    ],
}

DEPARTAMENTOS_POR_TIPO = {
    'A': DEPARTAMENTOS_TIPO_A,
    'B': DEPARTAMENTOS_TIPO_B,
    'C': DEPARTAMENTOS_TIPO_C,
    'D': DEPARTAMENTOS_TIPO_D,
    'E': DEPARTAMENTOS_TIPO_D,  # Tipo E usa mesma estrutura de D
}


def populate_organizational_structure(apps, schema_editor):
    """
    Cria a estrutura organizacional para todas as administrações existentes.
    Aplica retroativamente conforme o tipo de município.
    """
    Administracao = apps.get_model('ARQUIVOS', 'Administracao')
    Departamento = apps.get_model('ARQUIVOS', 'Departamento')
    Seccoes = apps.get_model('ARQUIVOS', 'Seccoes')
    
    for admin in Administracao.objects.all():
        tipo = admin.tipo_municipio
        departamentos = DEPARTAMENTOS_POR_TIPO.get(tipo, DEPARTAMENTOS_TIPO_D)
        
        print(f"\n[ADMIN] {admin.nome} (Tipo {tipo})")
        
        for dept_data in departamentos:
            # Verificar se já existe (evitar duplicatas)
            dept, created = Departamento.objects.get_or_create(
                nome=dept_data['nome'],
                administracao=admin,
                defaults={
                    'codigo': dept_data['codigo'],
                    'tipo_municipio': tipo,
                    'ativo': True,
                }
            )
            
            if created:
                print(f"  [+] {dept_data['nome']}")
                
                # Criar secções padrão se existirem
                seccoes = SECCOES_POR_DEPARTAMENTO.get(dept_data['codigo'], [])
                for seccao_nome in seccoes:
                    Seccoes.objects.get_or_create(
                        nome=seccao_nome,
                        departamento=dept,
                        defaults={'ativo': True}
                    )
                    print(f"      [+] {seccao_nome}")


def reverse_populate(apps, schema_editor):
    """Reverter não remove dados - muito arriscado"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0040_make_administracao_required'),
    ]

    operations = [
        migrations.RunPython(populate_organizational_structure, reverse_populate),
    ]
