# Generated by Django 4.2.11 on 2026-01-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0041_create_organizational_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministracaoMunicipal',
            fields=[
            ],
            options={
                'verbose_name': 'Administração Municipal',
                'verbose_name_plural': 'Administrações Municipais',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ARQUIVOS.administracao',),
        ),
        migrations.CreateModel(
            name='GovernoProvincial',
            fields=[
            ],
            options={
                'verbose_name': 'Governo Provincial',
                'verbose_name_plural': 'Governos Provinciais',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ARQUIVOS.administracao',),
        ),
        migrations.AlterField(
            model_name='administracao',
            name='tipo_municipio',
            field=models.CharField(choices=[('A', 'Tipo A'), ('B', 'Tipo B'), ('C', 'Tipo C'), ('D', 'Tipo D'), ('E', 'Tipo E'), ('G', 'Governo Provincial')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='tipo_municipio',
            field=models.CharField(choices=[('A', 'Tipo A'), ('B', 'Tipo B'), ('C', 'Tipo C'), ('D', 'Tipo D'), ('E', 'Tipo E'), ('G', 'Governo Provincial')], default='A', max_length=1),
        ),
    ]
