# Generated by Django 4.2.11 on 2026-02-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0042_administracaomunicipal_governoprovincial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministerio',
            fields=[
            ],
            options={
                'verbose_name': 'Ministério',
                'verbose_name_plural': 'Ministérios',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ARQUIVOS.administracao',),
        ),
        migrations.AlterField(
            model_name='administracao',
            name='tipo_municipio',
            field=models.CharField(choices=[('A', 'Tipo A'), ('B', 'Tipo B'), ('C', 'Tipo C'), ('D', 'Tipo D'), ('E', 'Tipo E'), ('G', 'Governo Provincial'), ('M', 'Ministério')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='tipo_municipio',
            field=models.CharField(choices=[('A', 'Tipo A'), ('B', 'Tipo B'), ('C', 'Tipo C'), ('D', 'Tipo D'), ('E', 'Tipo E'), ('G', 'Governo Provincial'), ('M', 'Ministério')], default='A', max_length=1),
        ),
    ]
