# Generated by Django 4.2.13 on 2025-09-05 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seccoes', to='ARQUIVOS.departamento'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='tipo_municipio',
            field=models.CharField(choices=[('A', 'Tipo A'), ('B', 'Tipo B'), ('C', 'Tipo C'), ('E', 'Tipo E')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='codigo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('nome', 'parent', 'tipo_municipio')},
        ),
    ]
