# Generated by Django 4.2.11 on 2025-12-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0005_alter_documento_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='Entidade',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documento',
            name='Telefone',
            field=models.IntegerField(default=1, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documento',
            name='Utente',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimentacaodocumento',
            name='tipo_movimentacao',
            field=models.CharField(choices=[('encaminhamento', 'Encaminhamento'), ('despacho', 'Despacho'), ('aprovado', 'Aprovado'), ('reprovado', 'reprovado'), ('arquivado', 'arquivado'), ('criacao', 'Criação'), ('recebimento', 'Recebimento')], default='encaminhamento', max_length=20),
        ),
    ]
