# Generated by Django 4.2.11 on 2025-12-20 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0006_documento_email_documento_entidade_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='tipo_municipio',
            field=models.CharField(choices=[('A', 'Tipo A'), ('B', 'Tipo B'), ('C', 'Tipo C'), ('D', 'Tipo D'), ('E', 'Tipo E')], default='A', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('nome', 'tipo_municipio')},
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='tipo_departamento',
        ),
        migrations.CreateModel(
            name='Seccoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('codigo', models.CharField(blank=True, max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ARQUIVOS.departamento')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Seccao_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Secção',
                'verbose_name_plural': 'Secções',
                'unique_together': {('nome', 'Departamento')},
            },
        ),
    ]
