# Generated by Django 4.2.11 on 2025-12-20 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0008_customuser_seccao_alter_customuser_nivel_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='seccao1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Secção', to='ARQUIVOS.seccoes'),
        ),
    ]
