# Generated by Django 4.2.11 on 2025-12-20 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0009_customuser_seccao1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='seccao1',
        ),
    ]
