# Generated by Django 4.2.11 on 2025-12-21 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0010_remove_customuser_seccao1'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaodocumento',
            name='seccao_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_recebidas', to='ARQUIVOS.seccoes'),
        ),
    ]
