# Generated by Django 4.2.11 on 2025-12-21 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0012_alter_customuser_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaodocumento',
            name='seccao_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_origem', to='ARQUIVOS.seccoes'),
        ),
        migrations.AlterField(
            model_name='movimentacaodocumento',
            name='seccao_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_destino', to='ARQUIVOS.seccoes'),
        ),
        migrations.AlterField(
            model_name='movimentacaodocumento',
            name='tipo_movimentacao',
            field=models.CharField(choices=[('criacao', 'Criação'), ('recebimento', 'Recebimento'), ('encaminhamento', 'Encaminhamento'), ('despacho', 'Despacho'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('arquivado', 'Arquivado')], default='encaminhamento', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimentacaodocumento',
            name='usuario_confirmacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmacoes_movimentacao', to=settings.AUTH_USER_MODEL),
        ),
    ]
