# Generated by Django 4.2.11 on 2025-12-21 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0013_movimentacaodocumento_seccao_origem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='seccao_atual',
            field=models.ForeignKey(blank=True, help_text='Secção específica onde o documento está atualmente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_atuais', to='ARQUIVOS.seccoes'),
        ),
    ]
