# Generated by Django 4.2.13 on 2026-01-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0017_alter_documento_data_prazo_alter_documento_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'verbose_name': 'Direção', 'verbose_name_plural': 'Direções'},
        ),
        migrations.AlterField(
            model_name='documento',
            name='Entidade',
            field=models.CharField(choices=[('Pessoa Singular', 'Pessoa Singular'), ('Instituição do Estado', 'Instituição do Estado'), ('Instituição Pública', 'Instituição Pública'), ('Instituição Privada', 'Instituição Privada'), ('Organização cívil', 'Organização cívil')], default='Pessoa Singular', max_length=52, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='Utente',
            field=models.CharField(max_length=200, verbose_name='Remetente'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='prioridade',
            field=models.CharField(choices=[('Normal', 'Normal 🟡'), ('Urgente', 'Urgente 🔴'), ('Muito Urgente', 'Muito Urgente 🔥')], default='normal', max_length=13),
        ),
        migrations.AlterField(
            model_name='documento',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Assunto'),
        ),
    ]
