# Generated by Django 4.2.13 on 2026-01-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0018_alter_departamento_options_alter_documento_entidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='nivels',
            field=models.CharField(choices=[('Público', 'Público'), ('Restrito', 'Restrito'), ('Confidencial', 'Confidencial')], default='Público', max_length=50, verbose_name='Niveis de Acesso'),
        ),
        migrations.AddField(
            model_name='documento',
            name='referencia',
            field=models.CharField(blank=True, help_text='referência', max_length=500),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tags',
            field=models.CharField(blank=True, help_text='Armazenamento', max_length=500),
        ),
    ]
