# Generated by Django 4.2.11 on 2026-01-12 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0020_documento_origem_alter_documento_entidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Província',
                'verbose_name_plural': 'Províncias',
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='departamento',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_departamento', to='ARQUIVOS.departamento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tags',
            field=models.CharField(blank=True, help_text='O numero do Armario pasta  Armario-1/doc-335', max_length=500),
        ),
        migrations.CreateModel(
            name='Administracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('A', 'Tipo A'), ('B', 'Tipo B'), ('C', 'Tipo C'), ('D', 'Tipo D')], max_length=1)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administracoes', to='ARQUIVOS.provincia')),
            ],
            options={
                'verbose_name': 'Administração',
                'verbose_name_plural': 'Administrações',
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='administracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos', to='ARQUIVOS.administracao'),
        ),
    ]
