# Generated by Django 4.2.11 on 2026-01-12 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0022_remove_administracao_provincia_municipio_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('nome', 'administracao')},
        ),
    ]
