# Generated by Django 4.2.11 on 2026-01-12 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0023_alter_departamento_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='administracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_administracao', to='ARQUIVOS.administracao'),
        ),
    ]
