# Generated by Django 4.2.11 on 2026-01-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0027_simplify_notificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='administracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo_municipio', models.CharField(choices=[('A', 'Tipo A'), ('B', 'Tipo B'), ('C', 'Tipo C'), ('D', 'Tipo D'), ('E', 'Tipo E')], default='A', max_length=1)),
            ],
        ),
    ]
