# Generated by Django 4.2.11 on 2026-01-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0028_administracao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administracao',
            options={'verbose_name': 'Administração', 'verbose_name_plural': 'Administrações'},
        ),
    ]
