# Generated by Django 4.2.11 on 2026-02-13 16:58

import ARQUIVOS.managers
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0029_alter_administracao_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministracaoMunicipal',
            fields=[
            ],
            options={
                'verbose_name': 'Administração Municipal',
                'verbose_name_plural': 'Administrações Municipais',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ARQUIVOS.administracao',),
        ),
        migrations.CreateModel(
            name='GovernoProvincial',
            fields=[
            ],
            options={
                'verbose_name': 'Governo Provincial',
                'verbose_name_plural': 'Governos Provinciais',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ARQUIVOS.administracao',),
        ),
        migrations.CreateModel(
            name='Ministerio',
            fields=[
            ],
            options={
                'verbose_name': 'Ministério',
                'verbose_name_plural': 'Ministérios',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ARQUIVOS.administracao',),
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', ARQUIVOS.managers.UsuarioManager()),
            ],
        ),
        migrations.RenameField(
            model_name='documento',
            old_name='nivels',
            new_name='niveis',
        ),
        migrations.RenameField(
            model_name='seccoes',
            old_name='Departamento',
            new_name='departamento',
        ),
        migrations.AlterUniqueTogether(
            name='seccoes',
            unique_together={('nome', 'departamento')},
        ),
        migrations.RemoveField(
            model_name='documento',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='Entidade',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='Telefone',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='Utente',
        ),
        migrations.AddField(
            model_name='administracao',
            name='provincia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='administracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios_administracao', to='ARQUIVOS.administracao'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='administracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departamentos_especificos', to='ARQUIVOS.administracao'),
        ),
        migrations.AddField(
            model_name='documento',
            name='administracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='ARQUIVOS.administracao'),
        ),
        migrations.AddField(
            model_name='documento',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documento',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='administracao',
            name='tipo_municipio',
            field=models.CharField(choices=[('A', 'Tipo A'), ('B', 'Tipo B'), ('C', 'Tipo C'), ('D', 'Tipo D'), ('E', 'Tipo E'), ('G', 'Governo Provincial'), ('M', 'Ministério')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='tipo_municipio',
            field=models.CharField(choices=[('A', 'Tipo A'), ('B', 'Tipo B'), ('C', 'Tipo C'), ('D', 'Tipo D'), ('E', 'Tipo E'), ('G', 'Governo Provincial'), ('M', 'Ministério')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='documento',
            name='arquivo_digitalizado',
            field=models.FileField(blank=True, null=True, upload_to='digitalizados/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='documento',
            name='status',
            field=models.CharField(choices=[('criacao', 'Criação'), ('recebimento', 'Recebimento'), ('encaminhamento', 'Encaminhamento'), ('despacho', 'Despacho'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('arquivado', 'Arquivado')], default='encaminhamento', max_length=20),
        ),
        migrations.AlterField(
            model_name='seccoes',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seccao_responsavel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('nome', 'administracao')},
        ),
        migrations.AddField(
            model_name='documento',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='documento',
            name='telefone',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'O telefone deve ter 9 dígitos.')]),
        ),
        migrations.AddField(
            model_name='documento',
            name='utente',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Remetente'),
        ),
    ]
