# Generated by Django 4.2.11 on 2026-02-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0030_administracaomunicipal_governoprovincial_ministerio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nivel_acesso',
            field=models.CharField(choices=[('admin_sistema', 'Administrador de Sistema'), ('ministro', 'Ministro'), ('secretario_estado', 'Secretário de Estado'), ('governador', 'Governador Provincial'), ('vice_governador', 'Vice-Governador'), ('admin_municipal', 'Administrador Municipal'), ('admin_adjunto', 'Administrador Adjunto'), ('diretor_nacional', 'Director Nacional e Equiparado'), ('chefe_departamento', 'Chefe de Departamento'), ('diretor_gabinete', 'Director de Gabinete Provincial e Equiparado'), ('diretor_municipal', 'Director Municipal e Equiparado'), ('chefe_seccao', 'Chefe de Secção'), ('tecnico', 'Técnico')], default='tecnico', max_length=30),
        ),
    ]
