# Generated by Django 4.2.11 on 2026-02-17 17:34

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0031_niveis_acesso_reestruturados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo',
            name='descricao',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='conteudo',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='documento',
            name='observacoes',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='movimentacaodocumento',
            name='despacho',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='movimentacaodocumento',
            name='observacoes',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='descricao',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
