# Generated by Django 4.2.11 on 2026-02-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0032_alter_anexo_descricao_alter_documento_conteudo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movimentacaodocumento',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
    ]
