# Generated by Django 4.2.11 on 2026-02-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0033_alter_documento_observacoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='conteudo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movimentacaodocumento',
            name='despacho',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
