# Generated by Django 5.0.14 on 2026-02-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0034_alter_documento_conteudo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nivel_sigilo',
            field=models.IntegerField(default=0, help_text='0=Técnico, 1=Chefia, 2=Direção'),
        ),
    ]
