# Generated by Django 5.0.14 on 2026-02-20 19:27

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0035_customuser_nivel_sigilo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='observacoes',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='movimentacaodocumento',
            name='tipo_movimentacao',
            field=models.CharField(choices=[('criacao', 'Criação'), ('recebimento', 'Recebimento'), ('encaminhamento', 'Encaminhado'), ('despacho', 'Despacho'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('arquivado', 'Arquivado')], default='encaminhamento', max_length=20),
        ),
    ]
