# Generated by Django 5.0.14 on 2026-02-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0036_change_observacoes_to_htmlfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='conteudo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
