# Generated by Django 5.0.14 on 2026-02-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0037_make_conteudo_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa 🟢'), ('normal', 'Normal 🟡'), ('alta', 'Alta 🟠'), ('urgente', 'Urgente 🔴'), ('muito_urgente', 'Muito Urgente 🔥')], default='normal', max_length=13),
        ),
    ]
