# Generated by Django 5.0.14 on 2026-02-20 20:46

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0038_align_priority_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='observacoes',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
