# Generated by Django 5.0.14 on 2026-02-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0039_make_observacoes_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='conteudo',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documento',
            name='observacoes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
