# Generated by Django 5.0.14 on 2026-02-20 21:43

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0040_revert_htmlfield_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo',
            name='descricao',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='conteudo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='observacoes',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
