# Generated by Django 5.0.14 on 2026-02-20 22:17

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0041_implement_rich_text_and_isolation_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='observacoes',
            field=models.CharField(blank=True, default='', help_text='Conteúdo do documento', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimentacaodocumento',
            name='despacho',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacaodocumento',
            name='observacoes',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
