# Generated by Django 5.0.14 on 2026-02-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0042_user_manual_fixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Conteúdo do documento', null=True),
        ),
    ]
