# Generated by Django 5.0.14 on 2026-03-01 22:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0043_observacoes_to_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='token_verificacao',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token único para verificação pública via QR Code', unique=True),
        ),
    ]
