# Generated by Django 5.0.14 on 2026-03-02 22:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0044_documento_token_verificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='administracao',
            name='origem_instancia',
            field=models.CharField(blank=True, default='', help_text="Identificador da instância que criou este registo (ex: 'admin_municipal_cabinda')", max_length=100),
        ),
        migrations.AddField(
            model_name='administracao',
            name='pendente_sinc',
            field=models.BooleanField(db_index=True, default=True, help_text='True se este registo ainda não foi sincronizado com o servidor central'),
        ),
        migrations.AddField(
            model_name='administracao',
            name='ultima_sincronizacao',
            field=models.DateTimeField(blank=True, help_text='Última vez que este registo foi sincronizado', null=True),
        ),
        migrations.AddField(
            model_name='administracao',
            name='uuid_sinc',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador universal para sincronização entre instâncias', unique=False),
        ),
        migrations.AddField(
            model_name='departamento',
            name='origem_instancia',
            field=models.CharField(blank=True, default='', help_text="Identificador da instância que criou este registo (ex: 'admin_municipal_cabinda')", max_length=100),
        ),
        migrations.AddField(
            model_name='departamento',
            name='pendente_sinc',
            field=models.BooleanField(db_index=True, default=True, help_text='True se este registo ainda não foi sincronizado com o servidor central'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='ultima_sincronizacao',
            field=models.DateTimeField(blank=True, help_text='Última vez que este registo foi sincronizado', null=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='uuid_sinc',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador universal para sincronização entre instâncias', unique=False),
        ),
        migrations.AddField(
            model_name='documento',
            name='origem_instancia',
            field=models.CharField(blank=True, default='', help_text="Identificador da instância que criou este registo (ex: 'admin_municipal_cabinda')", max_length=100),
        ),
        migrations.AddField(
            model_name='documento',
            name='pendente_sinc',
            field=models.BooleanField(db_index=True, default=True, help_text='True se este registo ainda não foi sincronizado com o servidor central'),
        ),
        migrations.AddField(
            model_name='documento',
            name='ultima_sincronizacao',
            field=models.DateTimeField(blank=True, help_text='Última vez que este registo foi sincronizado', null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='uuid_sinc',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador universal para sincronização entre instâncias', unique=False),
        ),
        migrations.AddField(
            model_name='movimentacaodocumento',
            name='estado_sync',
            field=models.CharField(choices=[('local', 'Criado Localmente'), ('pendente', 'Pendente de Sincronização'), ('sincronizado', 'Sincronizado')], default='sincronizado', help_text='Estado de sincronização: local (criado offline), pendente (aguarda sync), sincronizado (já propagado)', max_length=20),
        ),
        migrations.AddField(
            model_name='movimentacaodocumento',
            name='origem_instancia',
            field=models.CharField(blank=True, default='', help_text="Identificador da instância que criou este registo (ex: 'admin_municipal_cabinda')", max_length=100),
        ),
        migrations.AddField(
            model_name='movimentacaodocumento',
            name='pendente_sinc',
            field=models.BooleanField(db_index=True, default=True, help_text='True se este registo ainda não foi sincronizado com o servidor central'),
        ),
        migrations.AddField(
            model_name='movimentacaodocumento',
            name='sync_id',
            field=models.UUIDField(blank=True, help_text='UUID único para identificar a movimentação entre instâncias durante sincronização', null=True),
        ),
        migrations.AddField(
            model_name='movimentacaodocumento',
            name='ultima_sincronizacao',
            field=models.DateTimeField(blank=True, help_text='Última vez que este registo foi sincronizado', null=True),
        ),
        migrations.AddField(
            model_name='movimentacaodocumento',
            name='uuid_sinc',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador universal para sincronização entre instâncias', unique=False),
        ),
        migrations.AddField(
            model_name='movimentacaodocumento',
            name='via_sincronizacao',
            field=models.BooleanField(default=False, help_text='Indica se esta movimentação foi importada via sincronização offline'),
        ),
        migrations.AddField(
            model_name='seccoes',
            name='origem_instancia',
            field=models.CharField(blank=True, default='', help_text="Identificador da instância que criou este registo (ex: 'admin_municipal_cabinda')", max_length=100),
        ),
        migrations.AddField(
            model_name='seccoes',
            name='pendente_sinc',
            field=models.BooleanField(db_index=True, default=True, help_text='True se este registo ainda não foi sincronizado com o servidor central'),
        ),
        migrations.AddField(
            model_name='seccoes',
            name='ultima_sincronizacao',
            field=models.DateTimeField(blank=True, help_text='Última vez que este registo foi sincronizado', null=True),
        ),
        migrations.AddField(
            model_name='seccoes',
            name='uuid_sinc',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador universal para sincronização entre instâncias', unique=False),
        ),
    ]
