# Generated by Django 5.0.14 on 2026-03-05 20:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0049_customuser_origem_instancia_customuser_pendente_sinc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administracao',
            name='uuid_sinc',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador universal para sincronização entre instâncias', unique=True),
        ),
        migrations.AlterField(
            model_name='anexo',
            name='origem_instancia',
            field=models.CharField(blank=True, default='', help_text="Identificador da instância que criou este registo (ex: 'admin_municipal_cabinda')", max_length=100),
        ),
        migrations.AlterField(
            model_name='anexo',
            name='pendente_sinc',
            field=models.BooleanField(db_index=True, default=True, help_text='True se este registo ainda não foi sincronizado com o servidor central'),
        ),
        migrations.AlterField(
            model_name='anexo',
            name='ultima_sincronizacao',
            field=models.DateTimeField(blank=True, help_text='Última vez que este registo foi sincronizado', null=True),
        ),
        migrations.AlterField(
            model_name='anexo',
            name='uuid_sinc',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador universal para sincronização entre instâncias', unique=True),
        ),
        migrations.AlterField(
            model_name='armazenamentodocumento',
            name='origem_instancia',
            field=models.CharField(blank=True, default='', help_text="Identificador da instância que criou este registo (ex: 'admin_municipal_cabinda')", max_length=100),
        ),
        migrations.AlterField(
            model_name='armazenamentodocumento',
            name='pendente_sinc',
            field=models.BooleanField(db_index=True, default=True, help_text='True se este registo ainda não foi sincronizado com o servidor central'),
        ),
        migrations.AlterField(
            model_name='armazenamentodocumento',
            name='ultima_sincronizacao',
            field=models.DateTimeField(blank=True, help_text='Última vez que este registo foi sincronizado', null=True),
        ),
        migrations.AlterField(
            model_name='armazenamentodocumento',
            name='uuid_sinc',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador universal para sincronização entre instâncias', unique=True),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='origem_instancia',
            field=models.CharField(blank=True, default='', help_text="Identificador da instância que criou este registo (ex: 'admin_municipal_cabinda')", max_length=100),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='pendente_sinc',
            field=models.BooleanField(db_index=True, default=True, help_text='True se este registo ainda não foi sincronizado com o servidor central'),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='ultima_sincronizacao',
            field=models.DateTimeField(blank=True, help_text='Última vez que este registo foi sincronizado', null=True),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='uuid_sinc',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador universal para sincronização entre instâncias', unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='origem_instancia',
            field=models.CharField(blank=True, default='', help_text="Identificador da instância que criou este registo (ex: 'admin_municipal_cabinda')", max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pendente_sinc',
            field=models.BooleanField(db_index=True, default=True, help_text='True se este registo ainda não foi sincronizado com o servidor central'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ultima_sincronizacao',
            field=models.DateTimeField(blank=True, help_text='Última vez que este registo foi sincronizado', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='uuid_sinc',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador universal para sincronização entre instâncias', unique=True),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='uuid_sinc',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador universal para sincronização entre instâncias', unique=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='uuid_sinc',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador universal para sincronização entre instâncias', unique=True),
        ),
        migrations.AlterField(
            model_name='localarmazenamento',
            name='origem_instancia',
            field=models.CharField(blank=True, default='', help_text="Identificador da instância que criou este registo (ex: 'admin_municipal_cabinda')", max_length=100),
        ),
        migrations.AlterField(
            model_name='localarmazenamento',
            name='pendente_sinc',
            field=models.BooleanField(db_index=True, default=True, help_text='True se este registo ainda não foi sincronizado com o servidor central'),
        ),
        migrations.AlterField(
            model_name='localarmazenamento',
            name='ultima_sincronizacao',
            field=models.DateTimeField(blank=True, help_text='Última vez que este registo foi sincronizado', null=True),
        ),
        migrations.AlterField(
            model_name='localarmazenamento',
            name='uuid_sinc',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador universal para sincronização entre instâncias', unique=True),
        ),
        migrations.AlterField(
            model_name='movimentacaodocumento',
            name='uuid_sinc',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador universal para sincronização entre instâncias', unique=True),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='origem_instancia',
            field=models.CharField(blank=True, default='', help_text="Identificador da instância que criou este registo (ex: 'admin_municipal_cabinda')", max_length=100),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='pendente_sinc',
            field=models.BooleanField(db_index=True, default=True, help_text='True se este registo ainda não foi sincronizado com o servidor central'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='ultima_sincronizacao',
            field=models.DateTimeField(blank=True, help_text='Última vez que este registo foi sincronizado', null=True),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='uuid_sinc',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador universal para sincronização entre instâncias', unique=True),
        ),
        migrations.AlterField(
            model_name='seccoes',
            name='uuid_sinc',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador universal para sincronização entre instâncias', unique=True),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='origem_instancia',
            field=models.CharField(blank=True, default='', help_text="Identificador da instância que criou este registo (ex: 'admin_municipal_cabinda')", max_length=100),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='pendente_sinc',
            field=models.BooleanField(db_index=True, default=True, help_text='True se este registo ainda não foi sincronizado com o servidor central'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='ultima_sincronizacao',
            field=models.DateTimeField(blank=True, help_text='Última vez que este registo foi sincronizado', null=True),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='uuid_sinc',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador universal para sincronização entre instâncias', unique=True),
        ),
    ]
