# Generated by Django 5.0.14 on 2026-03-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0050_alter_administracao_uuid_sinc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administracao',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True, help_text='Data da última modificação local (usada para resolução de conflitos)', null=True),
        ),
        migrations.AddField(
            model_name='anexo',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True, help_text='Data da última modificação local (usada para resolução de conflitos)', null=True),
        ),
        migrations.AddField(
            model_name='armazenamentodocumento',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True, help_text='Data da última modificação local (usada para resolução de conflitos)', null=True),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True, help_text='Data da última modificação local (usada para resolução de conflitos)', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True, help_text='Data da última modificação local (usada para resolução de conflitos)', null=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True, help_text='Data da última modificação local (usada para resolução de conflitos)', null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True, help_text='Data da última modificação local (usada para resolução de conflitos)', null=True),
        ),
        migrations.AddField(
            model_name='localarmazenamento',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True, help_text='Data da última modificação local (usada para resolução de conflitos)', null=True),
        ),
        migrations.AddField(
            model_name='movimentacaodocumento',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True, help_text='Data da última modificação local (usada para resolução de conflitos)', null=True),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True, help_text='Data da última modificação local (usada para resolução de conflitos)', null=True),
        ),
        migrations.AddField(
            model_name='seccoes',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True, help_text='Data da última modificação local (usada para resolução de conflitos)', null=True),
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True, help_text='Data da última modificação local (usada para resolução de conflitos)', null=True),
        ),
    ]
