# Generated by Django 5.0.14 on 2026-03-24 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0051_administracao_data_modificacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administracao',
            name='contacto',
            field=models.TextField(blank=True, help_text='Email, Site e Telefone', null=True),
        ),
        migrations.AddField(
            model_name='administracao',
            name='endereco',
            field=models.TextField(blank=True, null=True),
        ),
    ]
