# Generated by Django 5.0.14 on 2026-04-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0052_administracao_contacto_administracao_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='nif',
            field=models.CharField(blank=True, help_text='Número de Identificação Fiscal / BI', max_length=14, null=True, verbose_name='NIF'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nivel_acesso',
            field=models.CharField(choices=[('admin_sistema', 'Administrador de Sistema'), ('ministro', 'Ministro'), ('secretario_estado', 'Secretário de Estado'), ('governador', 'Governador Provincial'), ('vice_governador', 'Vice-Governador'), ('admin_municipal', 'Administrador Municipal'), ('admin_adjunto', 'Administrador Adjunto'), ('diretor_nacional', 'Director Nacional e Equiparado'), ('chefe_departamento', 'Chefe de Departamento'), ('diretor_gabinete', 'Director de Gabinete Provincial e Equiparado'), ('diretor_municipal', 'Director Municipal e Equiparado'), ('chefe_seccao', 'Chefe de Secção'), ('secretario_admin', 'Secretário(a) do Administrador'), ('tecnico', 'Técnico')], default='tecnico', max_length=30),
        ),
    ]
