# Generated by Django 5.0.14 on 2026-04-24 22:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0053_documento_nif_alter_customuser_nivel_acesso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid_sinc', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador universal para sincronização entre instâncias', unique=True)),
                ('pendente_sinc', models.BooleanField(db_index=True, default=True, help_text='True se este registo ainda não foi sincronizado com o servidor central')),
                ('ultima_sincronizacao', models.DateTimeField(blank=True, help_text='Última vez que este registo foi sincronizado', null=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True, help_text='Data da última modificação local (usada para resolução de conflitos)', null=True)),
                ('origem_instancia', models.CharField(blank=True, default='', help_text="Identificador da instância que criou este registo (ex: 'admin_municipal_cabinda')", max_length=100)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome / Designação')),
                ('nif', models.CharField(blank=True, max_length=14, null=True, verbose_name='NIF / BI')),
                ('telefone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail')),
                ('tipo', models.CharField(choices=[('Pessoa Singular', 'Pessoa Singular'), ('Instituição do Estado', 'Instituição do Estado'), ('Instituição Pública', 'Instituição Pública'), ('Instituição Privada', 'Instituição Privada'), ('Organização cívil', 'Organização cívil')], default='Pessoa Singular', max_length=52, verbose_name='Tipo de Utente')),
                ('administracao', models.ForeignKey(blank=True, help_text='Opcional: Permite isolar os utentes por município.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utentes', to='ARQUIVOS.administracao')),
            ],
            options={
                'verbose_name': 'Utente / Entidade',
                'verbose_name_plural': 'Utentes e Entidades',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='remetente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='ARQUIVOS.utente'),
        ),
    ]
