# Generated by Django 5.0.14 on 2026-04-24 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0054_utente_documento_remetente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='email',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='nif',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='origem',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='utente',
        ),
    ]
